name: DSD-TF1
channels:
  - powerai
  - conda-forge
  - contango
  - defaults
dependencies:
  - python
  - tensorflow-gpu=1
  - tqdm
  - numpy
  - scipy
  - resampy
  - python_speech_features
  - tensorflow-gan
  - ipykernel
  - tensorflow-probability=0.7
  - matplotlib